-- Brief "Riportare in git ciò che vive solo nel database" (28/8/2026),
-- Passo 5: dati di riferimento, non dati operativi. Senza queste righe le
-- pagine dei reparti sono vuote e il battito non ha attese da controllare
-- in un ambiente nuovo. Idempotente: on conflict do nothing, applicarla due
-- volte non cambia il numero di righe.

insert into public.memoria_reparto (sigla, slug, scioglimento, denominazione, arma, certezza, sigla_padre, note) values
('1.GbArtRgt', '1-gebirgsartillerieregiment', 'Gebirgsartillerieregiment Nr. 1', '1° reggimento artiglieria da montagna', 'artiglieria', 'certa', null, null),
('1.KschRgt', '1-kaiserschuetzenregiment', null, null, 'fanteria alpina tirolese', 'da_verificare', 'I.KschRgt', 'I Kaiserschützen erano numerati solo I, II e III: probabile variante grafica di I.KschRgt.'),
('1/22.SappKp', '1-22-sappeurkompanie', '1. Kompanie, Sappeurbataillon Nr. 22', '1ª compagnia zappatori del 22° battaglione', 'genio', 'alta', null, null),
('1045.ArbAbtlg', '1045-arbeitsabteilung', 'Arbeitsabteilung Nr. 1045', '1045° reparto lavoratori', 'lavoro', 'certa', null, null),
('11.SchRgt', '11-schuetzenregiment', 'k.k. Schützenregiment Nr. 11', '11° reggimento fucilieri della Landwehr austriaca', 'fanteria', 'certa', null, null),
('12.GbArtRgt', '12-gebirgsartillerieregiment', 'Gebirgsartillerieregiment Nr. 12', '12° reggimento artiglieria da montagna', 'artiglieria', 'certa', null, null),
('12.SappBaon', '12-sappeurbataillon', 'Sappeurbataillon Nr. 12', '12° battaglione zappatori', 'genio', 'certa', null, null),
('122.FeldArtRgt', '122-feldartillerieregiment', 'Feldartillerieregiment Nr. 122', '122° reggimento artiglieria da campagna', 'artiglieria', 'certa', null, 'Convive con 122.GbArtRgt: verificare una possibile doppia lettura.'),
('122.GbArtRgt', '122-gebirgsartillerieregiment', 'Gebirgsartillerieregiment Nr. 122', '122° reggimento artiglieria da montagna', 'artiglieria', 'alta', null, 'Convive con 122.FeldArtRgt: verificare una possibile doppia lettura.'),
('13.IR', '13-infanterieregiment', 'Infanterieregiment Nr. 13', '13° reggimento di fanteria comune', 'fanteria', 'certa', null, null),
('130.FeldArtRgt', '130-feldartillerieregiment', 'Feldartillerieregiment Nr. 130', '130° reggimento artiglieria da campagna', 'artiglieria', 'certa', null, null),
('139.FeldArtRgt', '139-feldartillerieregiment', 'Feldartillerieregiment Nr. 139', '139° reggimento artiglieria da campagna', 'artiglieria', 'certa', null, 'Convive con 139.LndwhrKanRgt: verificare se sono la stessa unità.'),
('139.LndwhrKanRgt', '139-landwehr-kanonenregiment', 'Landwehr-Kanonenregiment Nr. 139', '139° reggimento cannoni della Landwehr', 'artiglieria', 'da_verificare', null, 'I reggimenti cannoni della Landwehr confluirono nella serie dell''artiglieria da campagna: possibile identità con 139.FeldArtRgt.'),
('14.IR', '14-infanterieregiment', 'Infanterieregiment Nr. 14', '14° reggimento di fanteria comune', 'fanteria', 'certa', null, null),
('143.FeldArtRgt', '143-feldartillerieregiment', 'Feldartillerieregiment Nr. 143', '143° reggimento artiglieria da campagna', 'artiglieria', 'certa', null, null),
('152.LndstBaon', '152-landsturmbataillon', 'Landsturmbataillon Nr. 152', '152° battaglione della milizia territoriale', 'milizia', 'alta', null, null),
('16.FeldJgrBaon', '16-feldjaegerbataillon', 'Feldjägerbataillon Nr. 16', '16° battaglione cacciatori da campo', 'cacciatori', 'certa', null, null),
('170.LndstrmInfBaon', '170-landsturm-infanteriebataillon', 'Landsturm-Infanteriebataillon Nr. 170', '170° battaglione fanteria della milizia', 'milizia', 'certa', null, null),
('173.LndstrmInfRgt', '173-landsturm-infanterieregiment', 'Landsturm-Infanterieregiment Nr. 173', '173° reggimento fanteria della milizia', 'milizia', 'alta', null, null),
('2.FestungArtRgt', '2-festungsartillerieregiment', 'Festungsartillerieregiment Nr. 2', '2° reggimento artiglieria da fortezza', 'artiglieria', 'certa', null, null),
('2.TKJgrRgt', '2-tiroler-kaiserjaegerregiment', 'Tiroler Kaiserjägerregiment Nr. 2', '2° reggimento Kaiserjäger tirolesi', 'fanteria alpina tirolese', 'certa', null, null),
('21.FeldKanRgt', '21-feldkanonenregiment', 'Feldkanonenregiment Nr. 21', '21° reggimento cannoni da campagna', 'artiglieria', 'certa', null, null),
('22.FeldArtRgt', '22-feldartillerieregiment', 'Feldartillerieregiment Nr. 22', '22° reggimento artiglieria da campagna', 'artiglieria', 'certa', null, null),
('22.FeldJgrBaon', '22-feldjaegerbataillon', 'Feldjägerbataillon Nr. 22', '22° battaglione cacciatori da campo', 'cacciatori', 'certa', null, null),
('22.GbArtRgt', '22-gebirgsartillerieregiment', 'Gebirgsartillerieregiment Nr. 22', '22° reggimento artiglieria da montagna', 'artiglieria', 'certa', null, null),
('23.LndstrmKmp', '23-landsturmkompanie', 'Landsturmkompanie Nr. 23', '23ª compagnia della milizia territoriale', 'milizia', 'alta', null, null),
('23.SchRgt', '23-schuetzenregiment', 'k.k. Schützenregiment Nr. 23', '23° reggimento fucilieri della Landwehr austriaca', 'fanteria', 'certa', null, null),
('26.SchRgt', '26-schuetzenregiment', 'k.k. Schützenregiment Nr. 26', '26° reggimento fucilieri della Landwehr austriaca', 'fanteria', 'certa', null, 'Fino al gennaio 1917 Landwehr-Infanterieregiment Nr. 26.'),
('3.bh.FeldJgrBaon', '3-bh-feldjaegerbataillon', 'bosnisch-hercegovinisches Feldjägerbataillon Nr. 3', '3° battaglione cacciatori bosniaco-erzegovese', 'cacciatori', 'certa', null, null),
('3.SchBaon', '3-schuetzenbataillon', 'Schützenbataillon Nr. 3', '3° battaglione fucilieri', 'fanteria', 'alta', null, null),
('3.SchRgt', '3-schuetzenregiment', 'k.k. Schützenregiment Nr. 3', '3° reggimento fucilieri della Landwehr austriaca', 'fanteria', 'certa', null, null),
('3.TrainBaon', '3-trainbataillon', 'Trainbataillon Nr. 3', '3° battaglione salmerie e trasporti', 'logistica', 'certa', null, null),
('3/39.FeldKanRgt', '3-39-feldkanonenregiment', '3. Batterie, Feldkanonenregiment Nr. 39', '3ª batteria del 39° reggimento cannoni da campagna', 'artiglieria', 'alta', null, null),
('32.SchRgt', '32-schuetzenregiment', 'k.k. Schützenregiment Nr. 32', '32° reggimento fucilieri della Landwehr austriaca', 'fanteria', 'certa', null, null),
('34.SchRgt', '34-schuetzenregiment', 'k.k. Schützenregiment Nr. 34', '34° reggimento fucilieri della Landwehr austriaca', 'fanteria', 'certa', null, null),
('35.SchRgt', '35-schuetzenregiment', 'k.k. Schützenregiment Nr. 35', '35° reggimento fucilieri della Landwehr austriaca', 'fanteria', 'certa', null, null),
('39.HonvedArtRgt', '39-honved-artillerieregiment', 'Honvéd-Feldartillerieregiment Nr. 39', '39° reggimento artiglieria della Honvéd ungherese', 'artiglieria', 'alta', null, null),
('4.TKJgrRgt', '4-tiroler-kaiserjaegerregiment', 'Tiroler Kaiserjägerregiment Nr. 4', '4° reggimento Kaiserjäger tirolesi', 'fanteria alpina tirolese', 'certa', null, null),
('43.FeldArtRgt', '43-feldartillerieregiment', 'Feldartillerieregiment Nr. 43', '43° reggimento artiglieria da campagna', 'artiglieria', 'certa', null, null),
('5.IR', '5-infanterieregiment', 'Infanterieregiment Nr. 5', '5° reggimento di fanteria comune', 'fanteria', 'certa', null, null),
('59.InfRgt', '59-infanterieregiment', 'Infanterieregiment Nr. 59', '59° reggimento di fanteria comune', 'fanteria', 'certa', null, 'Unico reggimento di fanteria scritto per esteso nel registro: stessa famiglia delle sigle IR.'),
('6.FeldJgrBaon', '6-feldjaegerbataillon', 'Feldjägerbataillon Nr. 6', '6° battaglione cacciatori da campo', 'cacciatori', 'certa', null, null),
('61.IR', '61-infanterieregiment', 'Infanterieregiment Nr. 61', '61° reggimento di fanteria comune', 'fanteria', 'certa', null, null),
('73.FliegerKp', '73-fliegerkompanie', 'Fliegerkompanie 73 (Flik 73)', '73ª compagnia aviatori', 'aviazione', 'certa', null, 'Cinque caduti: il reparto aereo più rappresentato nel cimitero.'),
('9.LndstrmInfBaon', '9-landsturm-infanteriebataillon', 'Landsturm-Infanteriebataillon Nr. 9', '9° battaglione fanteria della milizia', 'milizia', 'certa', null, null),
('9.TrainBaon', '9-trainbataillon', 'Trainbataillon Nr. 9', '9° battaglione salmerie e trasporti', 'logistica', 'certa', null, null),
('ArbAbtlg', 'arbeitsabteilung', 'Arbeitsabteilung', 'reparto lavoratori, numero non riportato dal registro', 'lavoro', 'certa', null, null),
('Eisenbahn', 'eisenbahn', null, 'truppe ferroviarie', 'ferrovia', 'da_verificare', null, 'La sigla dice solo "ferrovia": reggimento ferrovieri, compagnia da campo o reparto di esercizio.'),
('I.KschRgt', 'kaiserschuetzenregiment-i', 'Kaiserschützenregiment I', 'I reggimento Kaiserschützen', 'fanteria alpina tirolese', 'certa', null, 'Fino al gennaio 1917 Landesschützenregiment I.'),
('I.SchRgt', 'i-schuetzenregiment', 'k.k. Schützenregiment Nr. 1', '1° reggimento fucilieri della Landwehr austriaca', 'fanteria', 'certa', null, 'Sciolta dalla fonte: la Graeberliste del cimitero civile di Male, tomba 12, scrive per esteso "Schützen R.1" accanto a Josef Werndl. Non e il Kaiserschuetzenregiment I.'),
('I/170.LndstrmInfBaon', 'i-170-landsturm-infanteriebataillon', 'I. Baon, Landsturm-Infanterieregiment Nr. 170', 'I battaglione del 170° della milizia', 'milizia', 'da_verificare', '170.LndstrmInfBaon', 'Verificare se è sottounità del 170 o unità distinta.'),
('III.KschRgt', 'kaiserschuetzenregiment-iii', 'Kaiserschützenregiment III', 'III reggimento Kaiserschützen', 'fanteria alpina tirolese', 'certa', null, null),
('III.SchRgt', 'iii-schuetzenregiment', null, null, 'fanteria', 'da_verificare', null, 'Ambigua: Kaiserschützenregiment III oppure III battaglione di un reggimento fucilieri senza numero.'),
('IR', 'infanterieregiment', 'Infanterieregiment', 'reggimento di fanteria, numero non riportato dal registro', 'fanteria', 'certa', null, null),
('Russ.16.IR', 'russo-16-infanterieregiment', 'russisches Infanterieregiment Nr. 16', '16° reggimento di fanteria russo', 'esercito russo', 'certa', null, 'Prigioniero di guerra. Il prospetto del 1941 conta quattro russi nel cimitero militare.')
on conflict (sigla) do nothing;

insert into public.servizio (nome, descrizione, cadenza_massima_ore, attivo) values
('coda-ascolto-promemoria', 'Promemoria sulla coda delle registrazioni', 180, true),
('cruscotto-digest', 'Promemoria settimanale del cruscotto', 180, true),
('guardiani-digest', 'Digest dei contributi dei Guardiani', 180, true),
('radar-eventi-classifica', 'Classificazione degli eventi grezzi', 30, true),
('radar-eventi-harvest', 'Raccolta eventi dai 36 portali comunali', 30, true),
('sentinella-pagine', 'Controllo delle rotte pubbliche', 6, true),
('solleciti-domande', 'Solleciti sulle domande di tesseramento', 180, true),
('solleciti-quota', 'Solleciti sulle quote non versate', 180, true)
on conflict (nome) do nothing;
