-- Brief "Riportare in git ciò che vive solo nel database" (28/8/2026).
--
-- Fra il 26 e il 28 agosto dieci funzioni, quattro tabelle, sette viste e una
-- vista sostituita sono nate direttamente sul database via MCP, senza
-- passare da nessuna migrazione. Tutto già funziona in produzione: questa
-- migrazione non cambia nessun comportamento, trascrive lo stato attuale
-- (introspezione diretta: pg_get_functiondef, pg_get_viewdef,
-- information_schema, pg_policies, pg_constraint) perché sia riproducibile.
--
-- Perimetro: SOLO gli oggetti del 26-28 agosto elencati nel brief. La
-- fondazione del progetto (autenticazione, RLS, pgvector, pg_cron, ~33
-- migrazioni di aprile-maggio 2026) non ha alcun file in questo repository
-- e non viene toccata qui: vedi REPORT_migrazioni_recupero_2026-08-28.md.

-- =====================================================================
-- 1. TABELLE
-- =====================================================================

-- 1.1 servizio — registro dei servizi programmati che scrivono un battito
-- (brief "Il battito dei servizi", 28/8/2026). RLS attiva, NESSUNA policy:
-- solo le funzioni SECURITY DEFINER (registra_battito, cruscotto_servizi)
-- vi accedono, bypassando RLS come da proprietà. Nessun grant diretto.
create table if not exists public.servizio (
  nome                  text primary key,
  descrizione           text not null,
  cadenza_massima_ore   integer not null,
  attivo                boolean not null default true,
  creato_il             timestamptz not null default now()
);
alter table public.servizio enable row level security;
revoke all on public.servizio from anon, authenticated;

-- 1.2 servizio_battito — lo storico dei battiti. Stessa forma: RLS attiva,
-- nessuna policy, nessun grant diretto, accesso solo tramite le funzioni.
create table if not exists public.servizio_battito (
  id          bigint generated by default as identity primary key,
  servizio    text not null references public.servizio(nome) on delete cascade,
  esito       text not null check (esito in ('ok','errore','niente_da_fare')),
  dettaglio   jsonb,
  creato_il   timestamptz not null default now()
);
create index if not exists idx_battito_servizio_tempo on public.servizio_battito (servizio, creato_il desc);
alter table public.servizio_battito enable row level security;
revoke all on public.servizio_battito from anon, authenticated;

-- 1.3 memoria_reparto — scioglimento delle sigle di reparto per le pagine
-- dei cimiteri di guerra (brief "Cimiteri di guerra, la sezione completa",
-- 26/8/2026). Lettura pubblica (dato storico, non personale), scrittura
-- riservata a ruolo>=20 — stessa forma già in uso altrove nel progetto.
create table if not exists public.memoria_reparto (
  id             uuid primary key default gen_random_uuid(),
  sigla          text not null unique,
  slug           text not null unique,
  scioglimento   text,
  denominazione  text,
  arma           text,
  certezza       text not null default 'da_verificare' check (certezza in ('certa','alta','da_verificare')),
  sigla_padre    text,
  note           text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
alter table public.memoria_reparto enable row level security;
create policy memoria_reparto_lettura on public.memoria_reparto
  for select using (true);
create policy memoria_reparto_scrittura on public.memoria_reparto
  for all using (has_ruolo_min((select auth.uid()), 20));
-- Nessuna GRANT esplicita: la tabella eredita i privilegi di default dello
-- schema (anon: select/references/trigger; authenticated: tutti) già
-- stabiliti a livello di progetto (ALTER DEFAULT PRIVILEGES, fondazione
-- fuori da questo repository) — la stessa base su cui poggiano già le
-- altre tabelle "pubbliche" del progetto. La RLS sopra è ciò che restringe
-- davvero la scrittura.

-- 1.4 memoria_evento_reparto — collega un evento (es. un rastrellamento) ai
-- reparti coinvolti, con fonte e grado di confidenza dichiarati. Stessa
-- forma di accesso di memoria_reparto.
create table if not exists public.memoria_evento_reparto (
  id                       uuid primary key default gen_random_uuid(),
  evento_id                uuid not null references public.memoria_evento(id),
  sigla                    text,
  denominazione_documento  text not null,
  comando                  text,
  fonte                    text not null,
  citazione                text,
  confidenza               text not null default 'da_verificare' check (confidenza in ('certa','alta','media','da_verificare')),
  note                     text,
  created_at               timestamptz not null default now()
);
alter table public.memoria_evento_reparto enable row level security;
create policy mer_lettura on public.memoria_evento_reparto
  for select using (true);
create policy mer_scrittura on public.memoria_evento_reparto
  for all using (has_ruolo_min((select auth.uid()), 20));

-- =====================================================================
-- 2. COLONNE AGGIUNTE A memoria_persona
-- =====================================================================
-- Separazione fra registro storico e ricerca redazionale nostra (brief
-- "Cimiteri di guerra"): stessa_persona_di collega due righe che sono la
-- stessa persona registrata due volte; relazione_registrazione dice come;
-- nota_registrazione porta la nota libera; evento_motivazione la
-- motivazione redazionale distinta dal dato di registro (vedi `note`).
alter table public.memoria_persona
  add column if not exists stessa_persona_di uuid references public.memoria_persona(id),
  add column if not exists relazione_registrazione text,
  add column if not exists nota_registrazione text,
  add column if not exists evento_motivazione text;

alter table public.memoria_persona
  add constraint memoria_persona_relazione_reg_chk
  check (relazione_registrazione is null or relazione_registrazione in ('doppia_registrazione','doppia_sepoltura','da_verificare'));

-- evento_certezza esisteva già (colonna precedente, fuori da questo
-- perimetro): qui si trascrive solo il suo vincolo, comparso nella stessa
-- finestra e mai registrato.
alter table public.memoria_persona
  add constraint memoria_persona_evento_certezza_check
  check (evento_certezza is null or evento_certezza in ('attestato','sostenuto','probabile','non_sostenuto'));

-- =====================================================================
-- 3. FUNZIONI
-- =====================================================================

-- 3.1 / 3.2 — ascolto delle registrazioni (brief "La coda di ascolto", 26/8/2026)
create or replace function public.conferma_ascolto(p_audio_id uuid)
returns table(audio_id uuid, lemma_id uuid, lemma text, restanti bigint)
language plpgsql
security definer
set search_path to 'public'
as $function$
declare v_uid uuid := auth.uid(); v_lemma uuid;
begin
  if v_uid is null or not has_ruolo_min(v_uid, 20) then
    raise exception 'Non autorizzato ad ascoltare la coda';
  end if;

  select a.lemma_id into v_lemma from archivio_audio a
   where a.id = p_audio_id and a.stato = 'in_attesa' and a.ascoltato_il is null;
  if v_lemma is null then
    raise exception 'Registrazione non in coda o gia lavorata';
  end if;

  -- Il file va gia' copiato sul bucket pubblico dal chiamante prima di
  -- arrivare qui (supabase.storage.copy); questa funzione registra il
  -- risultato, non lo esegue: una funzione SQL non puo' chiamare la
  -- Storage API.
  update archivio_audio
     set stato = 'pubblicato', ascoltato_da = v_uid, ascoltato_il = now(), updated_at = now(),
         bucket = 'glossario-audio'
   where id = p_audio_id;

  update dizionario_lemma
     set audio_id = p_audio_id, updated_at = now()
   where id = v_lemma;

  return query
    select p_audio_id, v_lemma, l.lemma,
           (select count(*) from archivio_audio x
             where x.stato='in_attesa' and x.ascoltato_il is null)
      from dizionario_lemma l where l.id = v_lemma;
end $function$;
revoke execute on function public.conferma_ascolto(uuid) from public;
grant execute on function public.conferma_ascolto(uuid) to authenticated, service_role;

create or replace function public.scarta_ascolto(p_audio_id uuid, p_motivo text)
returns table(audio_id uuid, restanti bigint)
language plpgsql
security definer
set search_path to 'public'
as $function$
declare v_uid uuid := auth.uid();
begin
  if v_uid is null or not has_ruolo_min(v_uid, 20) then
    raise exception 'Non autorizzato ad ascoltare la coda';
  end if;
  if coalesce(btrim(p_motivo),'') = '' then
    raise exception 'Il motivo del rifiuto e obbligatorio';
  end if;

  update archivio_audio
     set stato = 'rifiutato', motivo_rifiuto = btrim(p_motivo),
         ascoltato_da = v_uid, ascoltato_il = now(), updated_at = now()
   where id = p_audio_id and stato = 'in_attesa' and ascoltato_il is null;

  if not found then raise exception 'Registrazione non in coda o gia lavorata'; end if;

  return query select p_audio_id,
    (select count(*) from archivio_audio x where x.stato='in_attesa' and x.ascoltato_il is null);
end $function$;
revoke execute on function public.scarta_ascolto(uuid, text) from public;
grant execute on function public.scarta_ascolto(uuid, text) to authenticated, service_role;

-- 3.3 registra_battito (brief "Il battito dei servizi", 28/8/2026):
-- SECURITY DEFINER senza controllo di ruolo interno — la restrizione è solo
-- a livello di GRANT/REVOKE, service_role soltanto (postgres, con cui gira
-- pg_cron, scavalca comunque ogni privilegio essendo superuser).
create or replace function public.registra_battito(p_servizio text, p_esito text default 'ok', p_dettaglio jsonb default null)
returns bigint
language plpgsql
security definer
set search_path to 'public'
as $function$
declare v_id bigint;
begin
  if not exists (select 1 from servizio where nome = p_servizio) then
    raise exception 'Servizio sconosciuto: %. Va prima registrato nella tabella servizio.', p_servizio;
  end if;
  insert into servizio_battito (servizio, esito, dettaglio)
  values (p_servizio, p_esito, p_dettaglio) returning id into v_id;
  return v_id;
end $function$;
revoke execute on function public.registra_battito(text, text, jsonb) from public;
grant execute on function public.registra_battito(text, text, jsonb) to service_role;

-- 3.4 lancia_radar_eventi / 3.5 lancia_radar_classifica / 3.6 controlla_radar_eventi
-- (brief "Radar eventi", chiamati dai lavori pg_cron del §4). Solo
-- service_role: sono lanciatori server-to-server, mai chiamati da un client.
create or replace function public.lancia_radar_eventi(p_esegui boolean default true, p_solo text default null::text)
returns text
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_token text; v_req bigint; v_url text;
begin
  select decrypted_secret into v_token from vault.decrypted_secrets where name = 'ingest_token';
  if v_token is null then
    return 'SOSPESO: il segreto ingest_token non e'' nel Vault. Nessuna raccolta avviata.';
  end if;

  v_url := 'https://wacknihvdjxltiqvxtqr.supabase.co/functions/v1/radar-eventi-harvest';
  if not p_esegui then
    v_url := v_url || '?dryrun=1';
    if p_solo is not null then v_url := v_url || '&solo=' || p_solo; end if;
  elsif p_solo is not null then
    v_url := v_url || '?solo=' || p_solo;
  end if;

  v_req := net.http_post(
    url := v_url,
    headers := jsonb_build_object('Content-Type','application/json','x-ingest-token', v_token),
    body := '{}'::jsonb,
    timeout_milliseconds := 120000
  );
  return format('richiesta %s inviata a %s', v_req, v_url);
end $function$;
revoke execute on function public.lancia_radar_eventi(boolean, text) from public;
grant execute on function public.lancia_radar_eventi(boolean, text) to service_role;

create or replace function public.lancia_radar_classifica(p_esegui boolean default true, p_digest boolean default false)
returns text
language plpgsql
security definer
set search_path to 'public'
as $function$
declare v_token text; v_req bigint; v_url text; v_grezzi int;
begin
  select decrypted_secret into v_token from vault.decrypted_secrets where name = 'ingest_token';
  if v_token is null then return 'SOSPESO: ingest_token assente dal Vault.'; end if;

  if not p_digest then
    select count(*) into v_grezzi from eventi_esterni where stato = 'grezzo';
    if v_grezzi = 0 then return 'NIENTE DA FARE: nessun evento in stato grezzo.'; end if;
  end if;

  v_url := 'https://wacknihvdjxltiqvxtqr.supabase.co/functions/v1/radar-eventi-classifica';
  if p_digest then v_url := v_url || '?digest=1' || case when p_esegui then '' else '&dryrun=1' end;
  elsif not p_esegui then v_url := v_url || '?dryrun=1';
  end if;

  v_req := net.http_post(
    url := v_url,
    headers := jsonb_build_object('Content-Type','application/json','x-ingest-token', v_token),
    body := '{}'::jsonb,
    timeout_milliseconds := 180000
  );
  return format('richiesta %s inviata (grezzi in coda: %s)', v_req, coalesce(v_grezzi::text,'n/d'));
end $function$;
revoke execute on function public.lancia_radar_classifica(boolean, boolean) from public;
grant execute on function public.lancia_radar_classifica(boolean, boolean) to service_role;

create or replace function public.controlla_radar_eventi()
returns text
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_ultima timestamptz; v_giorni int; v_token text; v_req bigint; v_msg text;
begin
  select max(created_at) into v_ultima
    from eventi_esterni where fonte in ('comunweb','dati_trentino');

  v_giorni := coalesce(extract(day from now() - v_ultima)::int, 999);
  if v_giorni < 4 then
    return format('OK: ultima raccolta %s giorni fa (%s)', v_giorni, v_ultima);
  end if;

  select decrypted_secret into v_token from vault.decrypted_secrets where name = 'ingest_token';
  if v_token is null then return 'ALLARME NON INVIATO: ingest_token assente dal Vault.'; end if;

  v_msg := format(
    'Il Radar eventi non porta niente di nuovo da %s giorni. Ultima raccolta: %s. Controlla i lavori pg_cron radar-eventi-harvest e radar-eventi-classifica.',
    v_giorni, coalesce(v_ultima::text, 'mai'));

  v_req := net.http_post(
    url := 'https://wacknihvdjxltiqvxtqr.supabase.co/functions/v1/send-email',
    headers := jsonb_build_object('Content-Type','application/json','X-Send-Email-Secret',
                 (select decrypted_secret from vault.decrypted_secrets where name='send_email_shared_secret')),
    body := jsonb_build_object(
      'to','info@elbrenz.eu',
      'subject','Radar eventi fermo da ' || v_giorni || ' giorni',
      'html','<p>' || v_msg || '</p>'),
    timeout_milliseconds := 20000);

  return format('ALLARME inviato (richiesta %s): %s', v_req, v_msg);
end $function$;
revoke execute on function public.controlla_radar_eventi() from public;
grant execute on function public.controlla_radar_eventi() to service_role;

-- 3.7 cruscotto_conta_domande (brief "Cruscotto del direttivo", 27/8/2026):
-- solo il conteggio, mai la vista domande_tesseramento intera.
create or replace function public.cruscotto_conta_domande()
returns table(in_attesa integer, piu_vecchia timestamptz)
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  -- Solo le domande davvero in lavorazione. 'annullata' e 'rifiutata' sono
  -- esiti finali: nessuno le sta aspettando.
  return query
  select count(*)::int, min(created_at)
  from domande_tesseramento
  where stato not in ('approvata','rifiutata','annullata');
end $function$;
revoke execute on function public.cruscotto_conta_domande() from public;
grant execute on function public.cruscotto_conta_domande() to authenticated, service_role;

-- 3.8 v_servizi_stato (vista interna, nessun grant) — deve esistere prima
-- di cruscotto_servizi(), che la legge.
create or replace view public.v_servizi_stato as
select s.nome,
       s.descrizione,
       s.cadenza_massima_ore,
       s.attivo,
       b.creato_il as ultimo_battito,
       b.esito as ultimo_esito,
       round(extract(epoch from now() - b.creato_il) / 3600.0, 1) as ore_fa,
       s.attivo and (b.creato_il is null or b.creato_il < (now() - make_interval(hours => s.cadenza_massima_ore)) or b.esito = 'errore') as in_allarme,
       case
         when b.creato_il is null then 'mai battuto'
         when b.esito = 'errore' then 'ultimo esito in errore'
         when b.creato_il < (now() - make_interval(hours => s.cadenza_massima_ore)) then 'silenzioso'
         else 'sano'
       end as diagnosi
from servizio s
left join lateral (
  select x.creato_il, x.esito from servizio_battito x
  where x.servizio = s.nome order by x.creato_il desc limit 1
) b on true;
-- Nessuna GRANT: vista interna, letta solo da cruscotto_servizi() (che
-- gira SECURITY DEFINER e quindi la vede comunque).

-- 3.9 cruscotto_servizi — il cancello: SECURITY DEFINER, verifica ruolo nel
-- corpo (allargata al service_role: vedi migrazione
-- 20260828032206_battito_cruscotto_servizi_service_role.sql, già in git).
create or replace function public.cruscotto_servizi()
returns table (servizio text, descrizione text, ultimo_battito timestamptz, ultimo_esito text, ore_fa numeric, cadenza_massima_ore integer, in_allarme boolean, diagnosi text)
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  if not (has_ruolo_min((select auth.uid()), 50) or (select auth.role()) = 'service_role') then
    raise exception 'Il cruscotto e riservato al direttivo';
  end if;
  return query
  select v.nome, v.descrizione, v.ultimo_battito, v.ultimo_esito, v.ore_fa,
         v.cadenza_massima_ore, v.in_allarme, v.diagnosi
  from v_servizi_stato v
  order by v.in_allarme desc, v.ore_fa desc nulls first, v.nome;
end $function$;
revoke execute on function public.cruscotto_servizi() from public;
grant execute on function public.cruscotto_servizi() to authenticated, service_role;

-- 3.10 cruscotto_funzioni — segnaposto voluto (vedi migrazione
-- 20260827212244_cruscotto_funzioni_dato_non_disponibile.sql, già in git,
-- che ne racconta il perché): resta a database, non più chiamata dalla
-- pagina, non cancellata. Qui solo per completezza dell'introspezione.
create or replace function public.cruscotto_funzioni()
returns table(funzione text, chiamate_30gg bigint, ultima timestamptz, ultimo_stato integer, giorni_fa numeric)
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  if not has_ruolo_min((select auth.uid()), 50) then
    raise exception 'Il cruscotto e riservato al direttivo';
  end if;
  return query
  select 'Dato non disponibile da Postgres — vedi il Logs Explorer di Supabase'::text,
         0::bigint, null::timestamptz, null::integer, null::numeric;
end $function$;
revoke execute on function public.cruscotto_funzioni() from public;
grant execute on function public.cruscotto_funzioni() to authenticated, service_role;

-- 3.11 v_cruscotto_code (usa cruscotto_conta_domande(), già creata sopra)
create or replace view public.v_cruscotto_code as
with q as (
  select 'Registrazioni da ascoltare'::text as coda, 'ascolta'::text as chiave, '/ascolta'::text as dove,
         count(*)::integer as in_attesa, min(archivio_audio.created_at) as piu_vecchia, 7 as soglia_giorni
    from archivio_audio
   where archivio_audio.stato = 'in_attesa' and archivio_audio.ascoltato_il is null
  union all
  select 'Eventi del radar da curare'::text, 'radar'::text, '/radar-eventi'::text,
         count(*)::integer, min(eventi_esterni.created_at), 14
    from eventi_esterni
   where eventi_esterni.stato = 'proposto'
  union all
  select 'Lemmi in attesa di validazione'::text, 'guardiani'::text, '/guardiani-curatela'::text,
         count(*)::integer, min(dizionario_lemma.created_at), 7
    from dizionario_lemma
   where dizionario_lemma.stato <> 'pubblicato'
  union all
  select 'Domande di tesseramento aperte'::text, 'domande'::text, '/tesseramento-curatela'::text,
         cd.in_attesa, cd.piu_vecchia, 5
    from cruscotto_conta_domande() cd(in_attesa, piu_vecchia)
)
select coda, chiave, dove, in_attesa, piu_vecchia,
       case when piu_vecchia is null then 0 else extract(day from now() - piu_vecchia)::integer end as giorni_ferma,
       soglia_giorni,
       in_attesa > 0 and piu_vecchia < (now() - make_interval(days => soglia_giorni)) as in_allarme
from q;
alter view public.v_cruscotto_code set (security_invoker = true);
revoke select on public.v_cruscotto_code from anon;
-- authenticated eredita il default (select + scritture inapplicabili a una
-- vista): coerente con lo stato dal vivo, verificato via
-- information_schema.role_table_grants prima di scrivere questa riga.

-- 3.12 cruscotto_lavori (letto dallo schema cron, fuori da public)
create or replace function public.cruscotto_lavori()
returns table(lavoro text, pianificazione text, attivo boolean, ultima_esecuzione timestamptz, esito text, ore_fa numeric, in_allarme boolean)
language plpgsql
security definer
set search_path to 'public', 'cron'
as $function$
begin
  if not (has_ruolo_min((select auth.uid()), 50) or (select auth.role()) = 'service_role') then
    raise exception 'Il cruscotto e riservato al direttivo';
  end if;
  return query
  select j.jobname::text,
         j.schedule::text,
         j.active,
         u.start_time,
         coalesce(u.status, 'mai eseguito')::text,
         round(extract(epoch from now() - u.start_time)/3600.0, 1),
         (u.start_time is null or u.status is distinct from 'succeeded' or u.start_time < now() - interval '8 days')
  from cron.job j
  left join lateral (
    select r.status, r.start_time from cron.job_run_details r
    where r.jobid = j.jobid order by r.start_time desc limit 1
  ) u on true
  where j.active
  order by j.jobname;
end $function$;
revoke execute on function public.cruscotto_lavori() from public;
grant execute on function public.cruscotto_lavori() to authenticated, service_role;

-- 3.13 v_cruscotto_completezza
create or replace view public.v_cruscotto_completezza as
select indicatore, fatti, totale, dove
from (values
  ('Lemmi con la voce agganciata'::text,
    (select count(*) from dizionario_lemma where dizionario_lemma.stato = 'pubblicato' and dizionario_lemma.audio_id is not null),
    (select count(*) from dizionario_lemma where dizionario_lemma.stato = 'pubblicato'),
    '/glossario-console'::text),
  ('Luoghi con il nome ladino validato'::text,
    (select count(*) from luoghi_interesse where luoghi_interesse.toponimo_validato_il is not null),
    (select count(*) from luoghi_interesse where luoghi_interesse.stato = 'pubblicato'),
    '/mappa'::text),
  ('Soci in regola collegati a un account'::text,
    ((select cruscotto_conta_soci_regola.fatti from cruscotto_conta_soci_regola() cruscotto_conta_soci_regola(fatti, totale))),
    ((select cruscotto_conta_soci_regola.totale from cruscotto_conta_soci_regola() cruscotto_conta_soci_regola(fatti, totale))),
    '/tesseramento-curatela'::text),
  ('Sepolture con data di morte'::text,
    (select count(*) from memoria_persona where memoria_persona.data_morte is not null),
    (select count(*) from memoria_persona),
    '/cimiteri-di-guerra'::text),
  ('Sigle di reparto sciolte'::text,
    (select count(*) from memoria_reparto where memoria_reparto.certezza <> 'da_verificare'),
    (select count(*) from memoria_reparto),
    '/cimiteri-di-guerra/male'::text)
) t(indicatore, fatti, totale, dove);
alter view public.v_cruscotto_completezza set (security_invoker = true);
revoke select on public.v_cruscotto_completezza from anon;

-- =====================================================================
-- 4. LE VISTE DELL'ARCHIVIO DEI REPARTI (dato pubblico, letto da anon)
-- =====================================================================

create or replace view public.v_memoria_reparto_pubblico as
select r.sigla, r.slug, r.scioglimento, r.denominazione, r.arma, r.certezza, r.sigla_padre, r.note,
       count(p.id) as caduti,
       count(p.id) filter (where p.settore = 'militare') as caduti_militare,
       count(p.id) filter (where p.settore = 'civile') as caduti_civile
from memoria_reparto r
left join memoria_persona p on p.reparto = r.sigla
group by r.sigla, r.slug, r.scioglimento, r.denominazione, r.arma, r.certezza, r.sigla_padre, r.note;
alter view public.v_memoria_reparto_pubblico set (security_invoker = true);
-- Nessuna revoca: dato storico pubblico, eredita il default (anon select).

create or replace view public.v_memoria_evento_reparto_pubblico as
select e.slug as evento_slug,
       mer.denominazione_documento, mer.comando, mer.sigla,
       r.slug as reparto_slug, r.denominazione as reparto_denominazione,
       mer.confidenza, mer.fonte, mer.citazione, mer.note,
       (select count(*) from memoria_persona p
         where p.reparto = mer.sigla and p.relazione_registrazione is distinct from 'doppia_registrazione') as sepolture_a_male
from memoria_evento_reparto mer
join memoria_evento e on e.id = mer.evento_id
left join memoria_reparto r on r.sigla = mer.sigla;
alter view public.v_memoria_evento_reparto_pubblico set (security_invoker = true);

create or replace view public.v_memoria_conteggi as
select
  count(*) filter (where settore = 'militare' and relazione_registrazione is distinct from 'doppia_registrazione') as sepolture_militari,
  count(*) filter (where settore = 'civile' and relazione_registrazione is distinct from 'doppia_registrazione') as sepolture_civili,
  count(*) filter (where relazione_registrazione is distinct from 'doppia_registrazione') as sepolture_totali,
  count(*) filter (where relazione_registrazione is null or relazione_registrazione = 'da_verificare') as uomini_distinti,
  count(*) filter (where relazione_registrazione = 'doppia_sepoltura') as uomini_in_entrambi_i_cimiteri,
  count(*) filter (where ignoto) as senza_nome,
  count(*) filter (where relazione_registrazione = 'da_verificare') as coppie_aperte,
  count(*) filter (where data_morte is not null) as con_data_di_morte
from memoria_persona;
alter view public.v_memoria_conteggi set (security_invoker = true);

-- =====================================================================
-- 5. v_coda_ascolto
-- =====================================================================
create or replace view public.v_coda_ascolto as
select a.id as audio_id, a.bucket, a.file_path, a.formato_audio, a.mime_originale,
       coalesce(a.durata_secondi, 0) as durata_secondi,
       a.parlata, a.comune_parlante, a.eta_parlante, a.sesso_parlante, a.nome_parlante,
       a.anonimo, a.voce_di_altri, a.consenso_parlante, a.registrato_il, a.luogo_registrazione, a.created_at,
       l.id as lemma_id, l.lemma, l.slug as lemma_slug, l.categoria_gramm, l.definizione, l.comune as lemma_comune,
       l.audio_id is not null as lemma_ha_gia_voce,
       row_number() over (order by a.created_at, a.id) as posizione,
       count(*) over () as totale,
       sum(coalesce(a.durata_secondi, 0)) over () as secondi_totali
from archivio_audio a
join dizionario_lemma l on l.id = a.lemma_id
where a.stato = 'in_attesa' and a.ascoltato_il is null;
alter view public.v_coda_ascolto set (security_invoker = true);
revoke all on public.v_coda_ascolto from anon;
revoke insert, update, delete, truncate, references, trigger on public.v_coda_ascolto from authenticated;
grant select on public.v_coda_ascolto to authenticated;

-- =====================================================================
-- 6. LA VISTA SOSTITUITA: v_memoria_persona_pubblica
-- =====================================================================
-- Esisteva già in forma più semplice (senza le colonne del §2). Ampliata
-- due volte in produzione, mai in una migrazione. Qui la forma attuale,
-- per intero: CREATE OR REPLACE è sicuro qualunque fosse la forma precedente.
create or replace view public.v_memoria_persona_pubblica as
select
  p.id, p.slug,
  f.slug as fondo_slug, f.slug_breve as fondo_slug_breve, f.titolo as fondo_titolo, f.comune, f.valle,
  p.settore, p.numero, p.nome_completo, p.grado, p.reparto,
  p.data_morte_testo, p.data_morte, p.anno_nascita, p.luogo_nascita, p.regione_nascita,
  p.prigioniero_guerra, p.ignoto, p.note,
  e.slug as evento_slug, e.nome as evento_nome, p.evento_certezza,
  p.relazione_registrazione,
  p.relazione_registrazione is distinct from 'doppia_registrazione' as conta_nei_totali,
  p.nota_registrazione,
  a.settore as altra_settore, a.numero as altra_numero, a.slug as altra_slug,
  r.denominazione as reparto_denominazione, r.scioglimento as reparto_scioglimento,
  r.slug as reparto_slug, r.certezza as reparto_certezza,
  p.evento_motivazione
from memoria_persona p
join memoria_fondo f on f.id = p.fondo_id
left join memoria_evento e on e.id = p.evento_id
left join memoria_persona a on a.id = p.stessa_persona_di
left join memoria_reparto r on r.sigla = p.reparto
where f.stato = 'pubblicato';
alter view public.v_memoria_persona_pubblica set (security_invoker = true);
-- Nessuna revoca: dato storico pubblico, come prima dell'ampliamento.
